### DISCUSSION TITLE
How to launch server with protocol v4?

### DISCUSSION THREAD

**Discussion by t0msk** [Totodore/socketioxide#325] [Q&A]
I am solving this issue: https://github.com/getnamo/SocketIOClient-Unreal/issues/425 that client for Unreal Engine supports only protocol v4 of SocketIO, and I cannot connect, so I think socketioxide uses v5 by default, so I would like to ask you how can I switch to v4 protocol my cargo.toml looks like:
`socketioxide = { version = "0.12", features = ["v4"] }`
but when I install packages, build it and run it, I still cannot connect to the server, so I wonder if my server is actually running v4 protocol or if there is some debug log that I can read what is happening.

**Comment by Totodore** [comment]
Hey ! Do you have any log from client or server side ? You can enable socketioxide logs with the tracing feature and add a tracing subscriber.
Check here for and example:
https://github.com/Totodore/socketioxide/blob/main/e2e/engineioxide/engineioxide.rs#L45-L49

**Reply by t0msk** [reply]
So I changed code like this:
```
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    tracing::subscriber::set_global_default(FmtSubscriber::default())?;

    let (layer, io) = SocketIo::new_layer();

    io.ns("/socket.io", on_connect);

    let app = axum::Router::new()
        .route("/", get(|| async { "Hello, World!" }))
        .route("/login", post(login))
        .layer(
            ServiceBuilder::new()
                .layer(CorsLayer::permissive()) // Enable CORS policy
                .layer(layer),
        );

    info!("Starting server");

    let listener = tokio::net::TcpListener::bind("0.0.0.0:3000").await.unwrap();

    #[cfg(feature = "v3")]
    tracing::info!("Starting server with v3 protocol");
    #[cfg(feature = "v4")]
    tracing::info!("Starting server with v4 protocol");

    axum::serve(listener, app).await.unwrap();

    Ok(())
}
```
but I didn't get anything in terminal, for the client side I don't have any logs yet.

for the server side (axum) I got just this:
```
╰─ cargo run                                                                                                                                                                 ─╯
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/server`
```

**Reply by Totodore** [reply]
You have to customize the options of `FmtSubscriber` to enable DEBUG mode like in the example I gave. And also enable the tracing feature

**Reply by t0msk** [reply]
do you mean like in Cargo.toml? because this is content of my cargo toml (I dont have many experiences with cargo):

```
[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.36.0", features = ["full"] }
axum = "0.7.4"
tower = "0.4.13"
tower-http = { version = "0.5.0", features = ["cors", "fs"] }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.108"
tracing-subscriber = { version = "0.3.18", features = ["fmt"] }
socketioxide = { version = "0.12", features = ["v4"] }
log = "^0"
tracing = "0.1.37"
```

**Reply by Totodore** [reply]
You have to have this for your main.rs file :
```rust
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let subscriber = FmtSubscriber::builder()
        .with_line_number(true)
        .with_max_level(Level::DEBUG)
        .finish();
    tracing::subscriber::set_global_default(subscriber)?;

    let (layer, io) = SocketIo::new_layer();

    io.ns("/socket.io", on_connect);

    let app = axum::Router::new()
        .route("/", get(|| async { "Hello, World!" }))
        .route("/login", post(login))
        .layer(
            ServiceBuilder::new()
                .layer(CorsLayer::permissive()) // Enable CORS policy
                .layer(layer),
        );

    info!("Starting server");

    let listener = tokio::net::TcpListener::bind("0.0.0.0:3000").await.unwrap();

    #[cfg(feature = "v3")]
    tracing::info!("Starting server with v3 protocol");
    #[cfg(feature = "v4")]
    tracing::info!("Starting server with v4 protocol");

    axum::serve(listener, app).await.unwrap();

    Ok(())
}
```

and this for your Cargo.toml file:
```toml
[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.36.0", features = ["full"] }
axum = "0.7.4"
tower = "0.4.13"
tower-http = { version = "0.5.0", features = ["cors", "fs"] }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.108"
tracing-subscriber = { version = "0.3.18", features = ["fmt"] }
socketioxide = { version = "0.12", features = ["v4", "tracing"] }
log = "^0"
tracing = "0.1.37"
```
